:schedule:
  :concurrency: 1
  
  user_worker:
    cron: '0 * * * * *'   # Runs once per minute
    class: UsersWorker

  welcome_email:
    cron: '0 10 * * 1'   # Runs once on every monday at 10:00am
    class: WelcomeEmail